Repository akroma-project/akroma.io, pull requests merged in 2018-03, with the labels that each got.

#48 feat: pp and tos
  src/app/shared/footer/footer.component.html
Labels: enhancement

#49 feat: add wallet link, add exchange link, fix medium link
  package-lock.json
  src/app/core/home/home.component.html
  src/app/core/home/home.component.scss
Labels: bug, enhancement

#50 feat: description
  src/index.html
Labels: bug, enhancement

#51 calling price API for price in USD
  src/app/app.module.ts
  src/app/explorer/explorer.module.ts
  src/app/explorer/models/price.ts
  src/app/explorer/pages/overview/overview.component.html
  src/app/explorer/pages/overview/overview.component.spec.ts
  src/app/explorer/pages/overview/overview.component.ts
  src/app/explorer/services/price.service.ts
Labels: enhancement

#52 Issue 23
  src/app/explorer/explorer.module.ts
  src/app/explorer/models/network.ts
  src/app/explorer/pages/overview/overview.component.html
  src/app/explorer/pages/overview/overview.component.spec.ts
  src/app/explorer/pages/overview/overview.component.ts
  src/app/explorer/services/network.service.ts
  src/environments/environment.ts
Labels: enhancement

#53 Task/#21 address transaction pagination
  src/app/explorer/explorer.module.ts
  src/app/explorer/models/address-transactions.ts
  src/app/explorer/pages/address-details/address-details.component.html
  src/app/explorer/pages/address-details/address-details.component.scss
  src/app/explorer/pages/address-details/address-details.component.spec.ts
  src/app/explorer/pages/address-details/address-details.component.ts
  src/app/explorer/services/addresses.service.ts
  src/assets/images/icon-arrow-left.svg
Labels: enhancement

#55 add 2 more mining pools
  src/app/core/home/home.component.html
Labels: enhancement

#57 update packages - security
  package-lock.json
  package.json
Labels: bug
